## We list different numpy methods here with simple examples

1) Importing numpy package to use its functionalities

In [1]:
import numpy as np

2) Creating a numpy 1D-Array and a 2D-Array from a list

In [18]:
list1D = [8, 1, 1991]
list1D_Numpy = np.array(list1D)
list2D = [[8, 1, 1991], [4, 5, 1991], [17, 3, 1948]]
list2D_Numpy = np.array(list2D)
print("Standart 1D-List :", list1D)
print("Numpy 1D-List :", list1D_Numpy)
print("Standart 2D-List :", list2D)
print("Numpy 2D-List :", list2D_Numpy)

Standart 1D-List : [8, 1, 1991]
Numpy 1D-List : [   8    1 1991]
Standart 2D-List : [[8, 1, 1991], [4, 5, 1991], [17, 3, 1948]]
Numpy 2D-List : [[   8    1 1991]
 [   4    5 1991]
 [  17    3 1948]]


3) Creating standard numpy list:
    -eye(n,p): 
    -zeros(n):
    -ones(n):
    -arange(n, m, h):
    -linspace(n, m, k):

In [52]:
print("Identity matrix with a size 10X10")
x = np.eye(10)
print(x)
print("Identity matrix with a size 3X3 + one extra zero column")
x = np.eye(3,4)
print(x)
print("Identity matrix with a size 10X6 by removing the 4th last columns")
x = np.eye(10,6)
print(x)
print("Row with 5 zeros")
x = np.zeros(5)
print(x)
print("Row with 5 ones")
x = np.ones(5)
print(x)
print("Row containing elements from 4 to strictly before 16 with 2 steps ")
x = np.arange(4,16,2)
print(x)
print("Row containing 11 elements from 0 to 100")
x = np.linspace(0, 100, 11)
print(x)

Identity matrix with a size 10X10
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Identity matrix with a size 3X3 + one extra zero column
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Identity matrix with a size 10X6 by removing the 4th last columns
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Row with 5 zeros
[0. 0. 0. 0. 0.]
Row with 5 ones
[1. 1. 1. 1. 1.]
Row containing elements from 4 to strictly before 16 with 2 steps 
[ 4  6  8 10 12 14]
Row containing 11 elements from 0 to 100
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
